title: meta
author:
name: CaptainTuesday
email: CaptainTuesday@protonmail.com

description: > # this means to ignore newlines until "show_excerpts:"
  built with coffee, chronic, corn, code & jekyll

show_excerpts: true # set to false to remove excerpts on the homepage

# social links
twitter_username: wipedroot # DO NOT include the @ character, or else the build will fail!
github_username:  wipedroot # DO NOT include the @ character, or else the build will fail!

remote_theme: Flexible-Jekyll
#remote_theme: jekyllt/jasper2.git

plugins:
 - jekyll-remote-theme
